language: go
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
install:
  - mkdir -p bin
  - ln -s /usr/bin/python3.5 bin/python3
  - export PATH=$PWD/bin:$PATH
script: make test
